/**
 * Entry Files Generator
 *
 * Generates the entry files for ai-knowledge package:
 * - AGENT.md: Usage guide for AI agents
 * - index.md: Global index listing all knowledge types
 */

import type {
  KnowledgePackageContribution,
  KnowledgePackageObjectRef,
} from "./knowledge-package-contribution.js";
import { DEFAULT_KNOWLEDGE_DIR, KNOWLEDGE_TYPES } from "../config/defaults.js";
import {
  TYPE_TO_DIR,
  getKnowledgeTypes,
  getDirForType,
  AllObjectType,
} from "../knowledge/type-directory-map.js";

/**
 * Generate AGENT.md content
 *
 * Design doc 03: AGENT.md is the first file an agent reads.
 * It should explain how to use the knowledge package.
 */
export function buildAgentMd(input: {
  repoName: string;
  generatedAt: string;
  knowledgeTypes: string[];
}): string {
  const { repoName, generatedAt, knowledgeTypes } = input;

  const lines = [
    `# ${repoName} - AI Knowledge Package`,
    "",
    "> 此知识包由 ai-wiki 自动生成，供 AI Agent 在开发流程中使用。",
    `> 生成时间：${generatedAt}`,
    "",
    "## 快速开始",
    "",
    "### 1. 检索顺序",
    "",
    "阅读知识包时，建议按以下顺序：",
    "",
    "1. **index.md** — 全局索引，了解有哪些知识和入口",
    "2. **capabilities/*.md** — 能力目录，理解仓库能做什么",
    "3. **concepts/*.md** — 概念知识，理解业务术语含义",
    "4. **constraints/*.md** — 约束知识，理解业务规则和限制",
    "5. **data-model/*.md** — 数据模型，理解实体关联",
    "6. **其他类型** — 按需深入",
    "",
    "### 2. 使用规则",
    "",
    "- **必须**：修改能力相关代码前，先阅读对应的能力目录文件",
    "- **必须**：使用证据引用定位代码位置，不要凭记忆猜测",
    "- **必须**：遇到未知的业务边界阻碍实现时停止，记录为开放问题",
    "- **禁止**：虚构不存在的能力、概念或约束",
    "",
    "## 知识类型说明",
    "",
    "| 类型 | 目录 | 用途 |",
    "|------|------|------|",
    "| 能力目录 | capabilities/ | 了解仓库能做什么、入口在哪 |",
    "| 概念知识 | concepts/ | 理解业务术语和枚举含义 |",
    "| 边界知识 | boundaries/ | 了解能力局限和禁用功能 |",
    "| 外部系统 | external-systems/ | 了解与外部系统的交互 |",
    "| 约束知识 | constraints/ | 理解业务规则和违反后果 |",
    "| 能力关系 | relations/ | 理解能力间的依赖和触发 |",
    "| 数据模型 | data-model/ | 理解实体聚合和关联 |",
    "| 跨域流程 | workflows/ | 理解跨能力的端到端流程 |",
    "",
    "## 文件结构",
    "",
    "```",
    `${DEFAULT_KNOWLEDGE_DIR}/`,
    "├── AGENT.md           # 本文件",
    "├── index.md           # 全局索引",
    "├── capabilities/      # 能力目录",
    "├── concepts/          # 概念知识",
    "├── boundaries/        # 边界知识",
    "├── external-systems/  # 外部系统交互",
    "├── constraints/       # 约束知识",
    "├── relations/         # 能力关系",
    "├── data-model/        # 数据模型",
    "├── workflows/         # 跨域业务流程",
    "├── evidence/          # 证据数据",
    "└── reports/           # 生成报告",
    "```",
    "",
    "## 更新机制",
    "",
    "知识包支持增量更新：",
    "- 当代码变更时，只重新生成受影响的知识条目",
    "- 保持未变更条目的稳定性",
    "- 使用 `.meta` 文件跟踪版本信息",
    "",
    "---",
    "",
    "*Generated by ai-wiki*",
  ];

  return lines.join("\n");
}

/**
 * Generate index.md content
 *
 * Design doc 03: index.md lists all knowledge types with their entries.
 */
export function buildIndexMd(input: {
  repoName: string;
  contributions: KnowledgePackageContribution[];
}): string {
  const { repoName, contributions } = input;

  // Collect all objects by type
  const objectsByDir: Record<string, KnowledgePackageObjectRef[]> = {};

  for (const contribution of contributions) {
    for (const obj of contribution.objects) {
      const dir = getDirForType(obj.type as AllObjectType);
      if (!objectsByDir[dir]) {
        objectsByDir[dir] = [];
      }
      objectsByDir[dir].push(obj);
    }
  }

  // Also collect files (primary docs)
  const filesByDir: Record<string, string[]> = {};
  for (const contribution of contributions) {
    for (const file of contribution.files) {
      // Extract directory from path
      const parts = file.path.split("/");
      if (parts.length > 1) {
        const dir = parts[0];
        if (!filesByDir[dir]) {
          filesByDir[dir] = [];
        }
        filesByDir[dir].push(file.path);
      }
    }
  }

  const lines = [
    `# ${repoName} - 知识库索引`,
    "",
    "Agent 读取知识库时第一个打开的文件。列出所有知识的概要，按需读取详情。",
    "",
  ];

  // Generate sections for each knowledge type
  const knowledgeTypes = getKnowledgeTypes();

  for (const type of knowledgeTypes) {
    const dir = TYPE_TO_DIR[type];
    const files = filesByDir[dir] ?? [];
    const objects = objectsByDir[dir] ?? [];

    if (files.length === 0 && objects.length === 0) {
      // Skip empty sections
      continue;
    }

    const typeLabel = getTypeLabel(type);

    lines.push(`## ${typeLabel}`);

    if (files.length > 0) {
      // Primary docs are markdown files
      lines.push("| 名称 | 文件 |");
      lines.push("|------|------|");
      for (const filePath of files.sort()) {
        const fileName = filePath.split("/").pop() ?? filePath;
        const name = fileName.replace(".md", "");
        lines.push(`| ${name} | [${filePath}](../${filePath}) |`);
      }
      lines.push("");
    }

    if (objects.length > 0) {
      // Objects are YAML files in objects/ subdirectory
      lines.push("| ID | 类型 | 文件 |");
      lines.push("|-----|------|------|");
      for (const obj of objects.sort((a, b) => a.id.localeCompare(b.id))) {
        const objDir = TYPE_TO_DIR[type] ?? "unknown";
        lines.push(
          `| ${obj.id} | ${type} | [objects/${objDir}/${obj.id}.yaml](../objects/${objDir}/${obj.id}.yaml) |`,
        );
      }
      lines.push("");
    }
  }

  // Add legacy types if present
  const legacyTypes = ["CON", "MOD", "OWN", "VER"];
  for (const type of legacyTypes) {
    const dir = getDirForType(type as AllObjectType);
    const objects = objectsByDir[dir] ?? [];

    if (objects.length === 0) {
      continue;
    }

    const typeLabel = getLegacyTypeLabel(type);

    lines.push(`## ${typeLabel}（兼容）`);
    lines.push("| ID | 类型 | 文件 |");
    lines.push("|-----|------|------|");
    for (const obj of objects.sort((a, b) => a.id.localeCompare(b.id))) {
      lines.push(
        `| ${obj.id} | ${type} | [objects/${dir}/${obj.id}.yaml](../objects/${dir}/${obj.id}.yaml) |`,
      );
    }
    lines.push("");
  }

  lines.push("---");
  lines.push("");
  lines.push("*Generated by ai-wiki*");

  return lines.join("\n");
}

/**
 * Get human-readable label for knowledge type
 */
function getTypeLabel(type: string): string {
  const labels: Record<string, string> = {
    CAPABILITY: "能力目录",
    CONCEPT: "概念知识",
    BOUNDARY: "边界知识",
    EXTERNAL: "外部系统交互",
    CONSTRAINT: "约束知识",
    RELATION: "能力关系",
    DATA_MODEL: "数据模型",
    WORKFLOW: "跨域业务流程",
  };
  return labels[type] ?? type;
}

/**
 * Get human-readable label for legacy type
 */
function getLegacyTypeLabel(type: string): string {
  const labels: Record<string, string> = {
    CON: "技术契约",
    MOD: "技术模块",
    OWN: "所有权",
    VER: "验证锚点",
  };
  return labels[type] ?? type;
}

/**
 * Generate entry files for the knowledge package
 */
export async function generateEntryFiles(input: {
  repoName: string;
  outputRoot: string;
  contributions: KnowledgePackageContribution[];
  generatedAt: string;
}): Promise<Array<{ path: string; content: string }>> {
  const { repoName, contributions, generatedAt } = input;

  // Collect all knowledge types present
  const presentTypes: Set<string> = new Set();
  for (const contribution of contributions) {
    for (const obj of contribution.objects) {
      presentTypes.add(obj.type);
    }
  }

  const agentMd = buildAgentMd({
    repoName,
    generatedAt,
    knowledgeTypes: Array.from(presentTypes),
  });

  const indexMd = buildIndexMd({
    repoName,
    contributions,
  });

  return [
    { path: "AGENT.md", content: agentMd },
    { path: "index.md", content: indexMd },
  ];
}
